<<<<<<<< HEAD:PythonTraining/路飞/Django/day16/app01/migrations/0019_school.py
# Generated by Django 4.1.3 on 2022-12-08 11:22
========
# Generated by Django 3.2 on 2023-07-15 14:31
>>>>>>>> 858832e11b2d0c3d7917587feb69c7631fbc95ce:Django/DJweb02/news/migrations/0001_initial.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_webcam_file_name'),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<<< HEAD:PythonTraining/路飞/Django/day16/app01/migrations/0019_school.py
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=12)),
========
            name='NewsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>>> 858832e11b2d0c3d7917587feb69c7631fbc95ce:Django/DJweb02/news/migrations/0001_initial.py
            ],
        ),
    ]
