# Generated by Django 4.1.3 on 2022-12-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_alter_shoujihao_certificates_nbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoujihao',
            name='CUST_NAME',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='shoujihao',
            name='USER_NAME',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
