# Generated by Django 4.1.3 on 2022-12-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_rename_lvevel_task_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webcam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.CharField(max_length=16)),
                ('file_path', models.CharField(max_length=64)),
                ('capture_date', models.DateTimeField()),
            ],
        ),
    ]
