# Generated by Django 4.1.3 on 2022-12-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_webcam'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcam',
            name='file_name',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
