# Generated by Django 3.2 on 2023-07-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='titile',
            new_name='title',
        ),
    ]
