# Generated by Django 2.2 on 2019-05-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='删除标记'),
        ),
        migrations.AlterField(
            model_name='typedetail',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='删除标记'),
        ),
    ]
