//
// Created by 武沛齐 on 2/24/22.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_nb_s2long_DynamicUtils */

jint plus(JNIEnv *env, jobject obj, jint v1, jint v2) {

    //    jclass clazz = (*env)->FindClass(env, "com/nb/fucker/DynamicUtils");
    //    jmethodID id = (*env)->GetMethodID(env, clazz, "", "(D)V");
    //    (*env)->NewObject(env,clazz,id)
    // 调用Java中类中的方法。
    return v1 + v2;
}


static JNINativeMethod gMethods[] = {
        {"add", "(II)I", (void *) plus},
};


JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *reserved) {


    JNIEnv *env = NULL;

    // 在java虚拟机中获取env
    if ((*vm)->GetEnv(vm, (void **) &env, JNI_VERSION_1_6) != JNI_OK) {
        return JNI_ERR;
    }


    // 找到Java中的类
    jclass clazz = (*env)->FindClass(env, "com/nb/s2long/DynamicUtils");

    // 将类中的方法注册到JNI中 (RegisterNatives)
    // clazz
    // gMethods ->  c <-> java
    int res = (*env)->RegisterNatives(env, clazz, gMethods, 1);
    if (res < 0) {
        return JNI_ERR;
    }

    return JNI_VERSION_1_6;
}
