# Generated by Django 4.2.5 on 2023-09-28 13:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='分类名称')),
                ('logo', models.ImageField(default='', upload_to='uploads/goods_img/', verbose_name='分类logo图片')),
                ('is_nav', models.BooleanField(default=False, verbose_name='是否显示在导航栏')),
                ('sort', models.IntegerField(verbose_name='排序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_cat', to='app8.goodscategory', verbose_name='父类')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='商品名称')),
                ('market_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='市场价格')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='实际价格')),
                ('createDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app8.goodscategory', verbose_name='商品分类')),
            ],
        ),
    ]
