# Generated by Django 4.2.5 on 2023-09-30 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app8', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品表'},
        ),
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'verbose_name': '商品分类'},
        ),
        migrations.AddField(
            model_name='goods',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='销售量'),
        ),
        migrations.AddField(
            model_name='goods',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
        migrations.AddField(
            model_name='goods',
            name='fav_num',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AddField(
            model_name='goods',
            name='is_recommend',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
        migrations.AddField(
            model_name='goods',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='商品主图'),
        ),
        migrations.AddField(
            model_name='goods',
            name='status',
            field=models.IntegerField(choices=[(0, '正常'), (1, '下架')], default=0),
        ),
        migrations.AddField(
            model_name='goods',
            name='stock_num',
            field=models.IntegerField(default=0, verbose_name='库存数'),
        ),
        migrations.AddField(
            model_name='goods',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='计量单位'),
        ),
        migrations.AddField(
            model_name='goods',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
