# Generated by Django 4.1.4 on 2022-12-12 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('app4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='部门编号')),
                ('departname', models.CharField(max_length=30, verbose_name='部门名称')),
                ('createdate', models.DateTimeField(db_column='createDate', verbose_name='创建日期')),
            ],
        ),
        migrations.AddField(
            model_name='userextrainfo',
            name='depart',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='app4.departinfo'),
        ),
    ]
