# Generated by Django 4.1.4 on 2022-12-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app4', '0002_departinfo_userextrainfo_depart'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='技能编号')),
                ('skillname', models.CharField(max_length=30, verbose_name='特长')),
                ('createdate', models.DateTimeField(db_column='createDate', verbose_name='创建日期')),
                ('user', models.ManyToManyField(db_table='user_skill', to='app4.userextrainfo')),
            ],
        ),
    ]
