# Generated by Django 4.1.4 on 2022-12-11 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imgfile',
            table=None,
        ),
    ]
