# Generated by Django 2.2 on 2019-05-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poetry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('detail', models.CharField(max_length=300, verbose_name='内容')),
            ],
        ),
    ]
