# Generated by Django 3.2 on 2023-07-17 12:27

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('image', models.ImageField(upload_to='', verbose_name='分类图标')),
                ('status', models.BooleanField(default=False, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '商品分类表',
                'verbose_name_plural': '商品分类表',
                'db_table': 'goods_group',
            },
        ),
        migrations.CreateModel(
            name='GoodsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(default='', help_text='轮播图名称', max_length=20, verbose_name='轮播图名称')),
                ('image', models.ImageField(blank=True, help_text='轮播图链接', null=True, upload_to='', verbose_name='轮播图链接')),
                ('status', models.BooleanField(blank=True, default=False, help_text='是否启用', verbose_name='是否启用')),
                ('seq', models.BooleanField(blank=True, default=1, help_text='顺序', verbose_name='顺序')),
            ],
            options={
                'verbose_name': '首页商品轮播',
                'verbose_name_plural': '首页商品轮播',
                'db_table': 'banner',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(default='', help_text='标题', max_length=200, verbose_name='标题')),
                ('desc', models.CharField(help_text='商品描述', max_length=200, verbose_name='商品描述')),
                ('price', models.DecimalField(decimal_places=2, help_text='商品价格', max_digits=10, verbose_name='商品价格')),
                ('cover', models.ImageField(default='', help_text='封面链接', null=True, upload_to='', verbose_name='封面图连接')),
                ('stock', models.IntegerField(blank=True, default=1, help_text='库存', verbose_name='库存')),
                ('sales', models.IntegerField(blank=True, default=0, help_text='销量', verbose_name='销量')),
                ('is_on', models.BooleanField(blank=True, default=False, help_text='是否上架', verbose_name='是否上架')),
                ('recommend', models.BooleanField(blank=True, default=False, help_text='是否推荐', verbose_name='是否推荐')),
                ('group', models.ForeignKey(help_text='分类', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='goods.goodgroup', verbose_name='分类')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('producer', models.CharField(help_text='厂商', max_length=200, verbose_name='厂商')),
                ('norms', models.CharField(help_text='规格', max_length=200, verbose_name='规格')),
                ('detail', ckeditor.fields.RichTextField(blank=True, verbose_name='商品详情')),
                ('goods', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品详情表',
                'verbose_name_plural': '商品详情表',
                'db_table': 'detail',
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('goods', models.ForeignKey(help_text='商品ID', on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品ID')),
                ('user', models.ForeignKey(blank=True, help_text='用户ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '收藏商品',
                'verbose_name_plural': '收藏商品',
                'db_table': 'collect',
            },
        ),
    ]
