# Generated by Django 3.2 on 2023-07-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodGroup',
            new_name='GoodsGroup',
        ),
    ]
