# Generated by Django 3.2 on 2023-07-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_rename_goodgroup_goodsgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsgroup',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='分类图标'),
        ),
    ]
