# Generated by Django 4.1.4 on 2022-12-20 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': (['check_diyuser', '审核用户信息'],)},
        ),
    ]
