# Generated by Django 4.1.3 on 2022-12-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_shoujihao_alter_prettynum_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoujihao',
            name='BUSI_NBR',
            field=models.CharField(max_length=32, verbose_name='号码'),
        ),
        migrations.AlterField(
            model_name='shoujihao',
            name='CERTIFICATES_NBR',
            field=models.CharField(max_length=32, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='shoujihao',
            name='CUST_ID',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='shoujihao',
            name='CUST_NAME',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='shoujihao',
            name='INSTALL_ADDR',
            field=models.CharField(max_length=32, verbose_name='安装地址'),
        ),
        migrations.AlterField(
            model_name='shoujihao',
            name='LATN',
            field=models.CharField(max_length=32, verbose_name='区号'),
        ),
        migrations.AlterField(
            model_name='shoujihao',
            name='PROD_INST_ID',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='shoujihao',
            name='USER_NAME',
            field=models.CharField(max_length=32),
        ),
    ]
