# Generated by Django 4.1.3 on 2022-12-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoujihao',
            name='CUST_ID',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='shoujihao',
            name='INSTALL_ADDR',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='安装地址'),
        ),
    ]
