# Generated by Django 4.1.3 on 2022-12-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_shoujihao_cust_id_alter_shoujihao_install_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoujihao',
            name='BUSI_NBR',
            field=models.CharField(db_index=True, max_length=32, verbose_name='号码'),
        ),
    ]
