# Generated by Django 4.1.3 on 2022-12-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_alter_shoujihao_busi_nbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=32, unique=True, verbose_name='标题'),
        ),
    ]
