# Generated by Django 4.1.3 on 2022-12-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_department_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoujihao',
            name='flag',
            field=models.SmallIntegerField(default=1, verbose_name='删除标志'),
        ),
    ]
