# Generated by Django 4.1.3 on 2022-12-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_shoujihao_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoujihao',
            name='flag',
        ),
        migrations.AddField(
            model_name='shoujihao',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='删除标志'),
        ),
    ]
