# Generated by Django 4.1.3 on 2022-12-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoujihao',
            name='CERTIFICATES_NBR',
            field=models.CharField(db_index=True, max_length=32, verbose_name='身份证号'),
        ),
    ]
