# Generated by Django 4.1.3 on 2022-12-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_alter_shoujihao_cust_name_alter_shoujihao_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='lvevel',
            new_name='level',
        ),
    ]
