# Generated by Django 4.1.3 on 2022-12-08 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcam',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.school', verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='capture_date',
            field=models.DateTimeField(verbose_name='截图时间'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='file_name',
            field=models.CharField(default=None, max_length=16, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='ipaddr',
            field=models.CharField(max_length=16, verbose_name='ip地址'),
        ),
    ]
