# Generated by Django 4.1.3 on 2022-12-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_webcam_school_alter_webcam_capture_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebcamPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50, verbose_name='文件名称')),
                ('md5sum', models.CharField(max_length=32, verbose_name='MD5值')),
                ('blob', models.BinaryField()),
                ('mod_time', models.DateTimeField(verbose_name='修改时间')),
            ],
        ),
    ]
