# Generated by Django 4.1.3 on 2022-12-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_alter_webcampic_md5sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcampic',
            name='file_name',
            field=models.CharField(max_length=128, verbose_name='文件名称'),
        ),
    ]
