# Generated by Django 4.1.4 on 2022-12-10 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('app01', '0023_alter_webcampic_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=64, verbose_name='订单号')),
                ('title', models.CharField(max_length=32, verbose_name='名称')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('status',
                 models.SmallIntegerField(choices=[(1, '未支付'), (2, '已支付')], default=1, verbose_name='订单状态')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin',
                                            verbose_name='管理员')),
            ],
        ),
    ]
