# Generated by Django 4.1.4 on 2022-12-11 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0024_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcampic',
            name='blob',
        ),
        migrations.RemoveField(
            model_name='webcampic',
            name='md5sum',
        ),
        migrations.RemoveField(
            model_name='webcampic',
            name='mod_time',
        ),
        migrations.AddField(
            model_name='webcampic',
            name='create_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间'),
        ),
        migrations.AddField(
            model_name='webcampic',
            name='img',
            field=models.FileField(default=None, upload_to='webcam', verbose_name='监控截图'),
        ),
    ]
