# Generated by Django 4.1.4 on 2022-12-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0025_remove_webcampic_blob_remove_webcampic_md5sum_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webcampic',
            options={'verbose_name': '监控截图'},
        ),
        migrations.AddField(
            model_name='webcampic',
            name='capture_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='截图时间'),
        ),
        migrations.AlterField(
            model_name='webcampic',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
    ]
