# Generated by Django 4.1.4 on 2022-12-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0026_alter_webcampic_options_webcampic_capture_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcampic',
            name='file_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='文件名称'),
        ),
    ]
