# Generated by Django 4.1.4 on 2022-12-12 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('app01', '0028_webcampic_ip_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcampic',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='app01.school', verbose_name='学校'),
        ),
        migrations.DeleteModel(
            name='Webcam',
        ),
    ]
