# Generated by Django 4.1.4 on 2022-12-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app01', '0029_webcampic_school_delete_webcam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoujihao',
            name='LATN',
            field=models.CharField(max_length=6, verbose_name='区号'),
        ),
        migrations.AlterField(
            model_name='shoujihao',
            name='mod_time',
            field=models.DateTimeField(db_index=True, verbose_name='采集时间'),
        ),
    ]
