# Generated by Django 4.1.4 on 2022-12-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app01', '0030_alter_shoujihao_latn_alter_shoujihao_mod_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoujihao',
            name='LATN',
            field=models.CharField(max_length=6, verbose_name='区号'),
        ),
    ]
