# Generated by Django 3.2 on 2023-01-07 09:25

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='商品名称')),
                ('market_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='市场价格')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='实际价格')),
                ('unit', models.CharField(blank=True, max_length=10, null=True, verbose_name='计量单位')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
                ('amount', models.IntegerField(default=0, verbose_name='销售量')),
                ('stock_num', models.IntegerField(default=0, verbose_name='库存数')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('goods_desc', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='商品详情')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '下架')], default=0)),
                ('main_img', models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='商品主图')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('createDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
                'db_table': 'd_goods',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='slide', verbose_name='轮播图片')),
                ('sort', models.IntegerField(default=0, verbose_name='排列顺序')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '首页轮播',
                'verbose_name_plural': '首页轮播',
                'db_table': 'd_slide',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='分类名称')),
                ('logo', models.ImageField(upload_to='uploads/goods_img/', verbose_name='分类logo图片')),
                ('is_nav', models.BooleanField(default=False, verbose_name='是否显示在导航栏')),
                ('sort', models.IntegerField(verbose_name='排序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_cat', to='goods.goodscategory', verbose_name='父类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'd_goods_category',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='goods.goodscategory', verbose_name='商品分类'),
        ),
    ]
