# Generated by Django 3.2 on 2023-01-05 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='main_img',
        ),
        migrations.RemoveField(
            model_name='goodscategory',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='images',
        ),
    ]
