# Generated by Django 3.1.5 on 2023-11-17 13:28

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='createDate',
        ),
        migrations.AddField(
            model_name='goods',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='商品详情'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '正常'), (1, '下架')], default=0),
        ),
        migrations.AlterField(
            model_name='slide',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
