# Generated by Django 3.1.5 on 2023-11-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20231117_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='logo',
            field=models.ImageField(blank=True, upload_to='uploads/goods_img/', verbose_name='分类logo图片'),
        ),
    ]
