# Generated by Django 3.2 on 2023-07-31 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0004_alter_collect_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('addr', models.CharField(max_length=200, verbose_name='收货地址')),
                ('order_code', models.CharField(help_text='订单编号', max_length=50, verbose_name='订单编号')),
                ('amount', models.FloatField(help_text='订单总金额', verbose_name='订单总金额')),
                ('status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '待发货'), (3, '配送中'), (4, '待评价'), (5, '已完成'), (6, '已关闭')], default=1, help_text='订单状态', verbose_name='订单状态')),
                ('pay_type', models.SmallIntegerField(choices=[(1, '支付宝'), (2, '微信支付'), (3, '云闪付'), (4, '货到付款')], default=1, help_text='支付方式', verbose_name='支付方式')),
                ('pay_time', models.DateTimeField(blank=True, help_text='支付时间', null=True, verbose_name='支付时间')),
                ('trade_no', models.CharField(blank=True, help_text='支付单号', max_length=50, null=True, verbose_name='支付单号')),
                ('user', models.ForeignKey(help_text='下单用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='下单用户')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('price', models.IntegerField(help_text='商品价格', verbose_name='商品价格')),
                ('number', models.IntegerField(default=1, help_text='商品数量', verbose_name='商品数量')),
                ('goods', models.ForeignKey(help_text='商品ID', on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品ID')),
                ('order', models.ForeignKey(help_text='所属订单', on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='所属订单')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
                'db_table': 'orderGoods',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('content', models.CharField(default='', max_length=150, verbose_name='评论内容')),
                ('rate', models.SmallIntegerField(blank=True, choices=[(1, '好评'), (2, '好评'), (1, '好评')], default=1, help_text='评论等级', verbose_name='评论等级')),
                ('star', models.SmallIntegerField(blank=True, choices=[(1, '一星'), (2, '二星'), (3, '三星'), (4, '四星'), (5, '五星')], default=5, verbose_name='评论星级')),
                ('goods', models.ForeignKey(help_text='所属商品', on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='所属商品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='所属订单')),
                ('user', models.ForeignKey(help_text='评论用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户')),
            ],
            options={
                'verbose_name': '订单评论',
                'verbose_name_plural': '订单评论',
                'db_table': 'comment',
            },
        ),
    ]
