# Generated by Django 3.2 on 2023-07-20 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=19, verbose_name='手机号')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
                ('info', models.CharField(max_length=200, verbose_name='详细地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.userinfo', verbose_name='所属用户')),
            ],
        ),
    ]
