"""
<<<<<<<< HEAD:PythonTraining/路飞/Django/mysite2/mysite2/settings.py
Django settings for mysite2 project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
========
Django settings for baykeproject project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
>>>>>>>> 858832e11b2d0c3d7917587feb69c7631fbc95ce:Django/轻编程/bayke-shop/baykeproject/settings.py
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
<<<<<<<< HEAD:PythonTraining/路飞/Django/mysite2/mysite2/settings.py
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r_08y62_+3%ey%rputim@ly0xy8@y3gh6gm0$)v_b-#x4tm=f2'
========
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tix9bzpxoi%+v4w3v_rm$7jk4tehodfw%mmquzmfk_a_i#dvf*'
>>>>>>>> 858832e11b2d0c3d7917587feb69c7631fbc95ce:Django/轻编程/bayke-shop/baykeproject/settings.py

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'baykeshop.apps.article'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

<<<<<<<< HEAD:PythonTraining/路飞/Django/mysite2/mysite2/settings.py
ROOT_URLCONF = 'mysite2.urls'
========
ROOT_URLCONF = 'baykeproject.urls'
>>>>>>>> 858832e11b2d0c3d7917587feb69c7631fbc95ce:Django/轻编程/bayke-shop/baykeproject/settings.py

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

<<<<<<<< HEAD:PythonTraining/路飞/Django/mysite2/mysite2/settings.py
WSGI_APPLICATION = 'mysite2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
========
WSGI_APPLICATION = 'baykeproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
>>>>>>>> 858832e11b2d0c3d7917587feb69c7631fbc95ce:Django/轻编程/bayke-shop/baykeproject/settings.py

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
<<<<<<<< HEAD:PythonTraining/路飞/Django/mysite2/mysite2/settings.py
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators
========
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
>>>>>>>> 858832e11b2d0c3d7917587feb69c7631fbc95ce:Django/轻编程/bayke-shop/baykeproject/settings.py

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
<<<<<<<< HEAD:PythonTraining/路飞/Django/mysite2/mysite2/settings.py
# https://docs.djangoproject.com/en/4.1/topics/i18n/
========
# https://docs.djangoproject.com/en/4.2/topics/i18n/
>>>>>>>> 858832e11b2d0c3d7917587feb69c7631fbc95ce:Django/轻编程/bayke-shop/baykeproject/settings.py

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
<<<<<<<< HEAD:PythonTraining/路飞/Django/mysite2/mysite2/settings.py
# https://docs.djangoproject.com/en/4.1/howto/static-files/
========
# https://docs.djangoproject.com/en/4.2/howto/static-files/
>>>>>>>> 858832e11b2d0c3d7917587feb69c7631fbc95ce:Django/轻编程/bayke-shop/baykeproject/settings.py

STATIC_URL = 'static/'

# Default primary key field type
<<<<<<<< HEAD:PythonTraining/路飞/Django/mysite2/mysite2/settings.py
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field
========
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
>>>>>>>> 858832e11b2d0c3d7917587feb69c7631fbc95ce:Django/轻编程/bayke-shop/baykeproject/settings.py

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
