# Generated by Django 2.2.28 on 2022-12-07 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('learning_logs', '0002_auto_20221207_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
