# Generated by Django 3.2 on 2023-01-19 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogarticles',
            options={'ordering': ['-publish'], 'verbose_name': 'Article'},
        ),
    ]
