# Generated by Django 4.2.4 on 2023-10-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.FloatField(blank=True, null=True, verbose_name='豆瓣评分'),
        ),
    ]
